# Generated by Django 5.2.5 on 2025-11-14 20:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('patente', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('motor', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('idProvincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProvincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRegion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de Farmacia')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discopro.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Mantenimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción del Mantenimiento')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('taller', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taller')),
                ('kilometraje', models.IntegerField(blank=True, null=True, verbose_name='Kilometraje')),
                ('factura', models.FileField(blank=True, null=True, upload_to='mantenimientos/', verbose_name='Factura/Comprobante')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='discopro.moto')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionMoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField(default=2025, verbose_name='Año del Permiso de Circulación')),
                ('permiso_circulacion_file', models.FileField(blank=True, null=True, upload_to='documentos_moto/permiso_circulacion/', verbose_name='Permiso de Circulación (Archivo)')),
                ('permiso_circulacion_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento Permiso de Circulación')),
                ('seguro_obligatorio_file', models.FileField(blank=True, null=True, upload_to='documentos_moto/seguro_obligatorio/', verbose_name='Seguro Obligatorio (Archivo)')),
                ('seguro_obligatorio_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento Seguro Obligatorio')),
                ('revision_tecnica_file', models.FileField(blank=True, null=True, upload_to='documentos_moto/revision_tecnica/', verbose_name='Revisión Técnica (Archivo)')),
                ('revision_tecnica_vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento Revisión Técnica')),
                ('moto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentacion', to='discopro.moto')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('pasaporte', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('licencia_conducir', models.FileField(blank=True, null=True, upload_to='licencias/')),
                ('fecha_ultimo_control', models.DateField(blank=True, null=True)),
                ('fecha_proximo_control', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('licencia', 'Con Licencia Médica')], default='activo', max_length=20, verbose_name='Estado')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discopro.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('idDocumentacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDocumento', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='documentos_motorista/')),
                ('fechaVencimiento', models.DateField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='discopro.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('idContacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('parentesco', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='discopro.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionMoto',
            fields=[
                ('idAsignacionMoto', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAsignacion', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='Asignada', max_length=50)),
                ('fechaTermino', models.DateField(blank=True, null=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discopro.moto')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discopro.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionFarmacia',
            fields=[
                ('idAsignacionFarmacia', models.AutoField(primary_key=True, serialize=False)),
                ('fechaAsignacion', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaTermino', models.DateField(blank=True, null=True)),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discopro.farmacia')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discopro.motorista')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discopro.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discopro.region'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discopro.rol')),
            ],
        ),
    ]
