# Generated by Django 5.2.8 on 2025-11-21 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discopro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionfarmacia',
            name='fechaAsignacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asignacionmoto',
            name='fechaAsignacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
