# Generated by Django 5.2.8 on 2025-11-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discopro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
    ]
