# Generated by Django 5.2.5 on 2025-11-15 00:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discopro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('idTipoMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador único')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del movimiento')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Descripción / Observación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('anulado', 'Anulado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('origen', models.CharField(max_length=255, verbose_name='Origen (Bodega/sector que entrega)')),
                ('destino', models.CharField(max_length=255, verbose_name='Destino (Bodega/sector que recibe)')),
                ('motorista_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discopro.motorista', verbose_name='Motorista Asignado')),
                ('movimiento_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramos_hijos', to='discopro.movimiento', verbose_name='Movimiento Padre (Despacho)')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discopro.usuario', verbose_name='Usuario Responsable (Operador)')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discopro.tipomovimiento', verbose_name='Tipo de Movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
