# Generated by Django 5.2.8 on 2025-11-20 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discopro', '0002_alter_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='numero_despacho',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Despacho (Cruz Verde)'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='destino',
            field=models.CharField(max_length=255, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_movimiento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id_movimiento',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador Interno'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='movimiento_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tramos_hijos', to='discopro.movimiento', verbose_name='Movimiento Padre'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='origen',
            field=models.CharField(max_length=255, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='usuario_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discopro.usuario', verbose_name='Usuario Responsable'),
        ),
    ]
