# Generated by Django 5.2.8 on 2025-11-21 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discopro', '0002_alter_asignacionfarmacia_fechaasignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
    ]
